trigger: none
pool: agentpool
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    backendServiceArm: 'sc'
    backendAzureRmStorageAccountName: 'bhushan123'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'dev-terraform.tfstate'
- task: TerraformTask@5
  displayName: terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
