trigger: none
jobs:
- job: firstjob # Required as first property. ID of the job.
  displayName: Terraform init # Human-readable name for the job.
  pool: agentpool
  steps: 
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTask@5
    displayName: initwa
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
      backendServiceArm: 'sc'
      backendAzureRmResourceGroupName: 'chandra-rg'
      backendAzureRmStorageAccountName: 'bhushan123'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'dev-terraform.tfstate'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
      environmentServiceNameAzureRM: 'sc'
- job: secondjob
  displayName: manualapproval
  pool: server
  steps:
  - task: ManualValidation@1
    inputs:
      notifyUsers: 'chandrapratap.smsit@gmail.com'
# - job: thirdjob
#   displayName: terraformapply
#   pool: agentpool
#   steps:

